
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: db           #endpoint의 ports의 name와 일치해야함.
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: mysql
subsets:
- addresses:
  - ip: 169.56.100.106
  ports:
  - port: 3306
    name: db             #service의 ports의 name와 일치해야함.
